---
- name: "Configuration complète de l'infrastructure"
  hosts: all
  become: yes

  roles:
    - common

  tasks:
    - name: "Setup VM-0"
      when: inventory_hostname == "vm-0"
      block:
        - include_role:
            name: user_management
          vars:
            custom_user: "{{ lookup('env', 'CUSTOM_USER_WEB') }}"
        - include_role:
            name: web_server

    - name: "Setup VM-1"
      when: inventory_hostname == "vm-1"
      block:
        - include_role:
            name: user_management
          vars:
            custom_user: "{{ lookup('env', 'CUSTOM_USER_ADMIN') }}"
        - include_role:
            name: admin_tools
      